name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/williamhorning/gokrazy-homeassistant:${{ github.sha }}
            ghcr.io/williamhorning/gokrazy-homeassistant:latest
